#pragma once

#define CAMERA_UP    "EBA500BE"
#define CAMERA_DOWN   "EBA600BE"
#define CAMERA_RESET "EBA000BE"
//#define CAMERA_OMOVEM_FAST "EBA1"
#define AIR_PRESSURE_CHECK  "EBAB00BE"
#define AIR_OPEN "EBA700BE"
#define AIR_CLOSE "EBA800BE"
#define MAT_UP "EBA900BE"
#define MAT_DOWN "EBAA00BE"
#define PRESS_UPORDOWN "EBAC00BE"
#define LIGHT_OFF "EBAD0100BE"
#define LIGHT_RED "EBAD0103BE"
#define LIGHT_GREEN "EBAD0101BE"
#define LIGHT_YELLOW "EBAD0102BE"
#define LIGHT_WARRING "EBAD0104BE"

#define BOX_RESET "EBC000BE"
#define BOX_STATUS_FREE "EBC100BE"
#define BOX_STATUS_BUSY "EBC200BE"
#define BOX_OUT "EBC300BE"
#define BOX_IN "EBC400BE"


#define PROP_RESET "EBB000BE"
#define PROP_MOVE_RESET "EBB100BE"
